package main

import (
	"github.com/vapourlang/vapour/config"
	"github.com/vapourlang/vapour/lexer"
)

type vapour struct {
	name    string
	version string
	root    *string
	files   lexer.Files
	config  *config.Config
}

func New() *vapour {
	return &vapour{
		name:    "vapour",
		version: "0.0.4",
	}
}

func addHeader(code string) string {
	return "# GENERATED BY VAPOUR\n# DO NOT EDIT\n" + code
}
