# GENERATED BY VAPOUR
# DO NOT EDIT
globals = new.env(parent=emptyenv(), hash=TRUE)



write_config = function() {

config = structure(list(types=globals$types, yields=globals$yields), class=c("Config", "list"))



print(config)

}
#' Type
#'
#' Add type to the roxygen2 documentation.
#'
#' @importFrom roxygen2 roclet roxy_tag_warning block_get_tags roclet_output
#' @importFrom roxygen2 roclet_process roxy_tag_parse rd_section roxy_tag_rd
#'
#' @import roxygen2
#'
#' @export
roclet_type = function() {


return(roxygen2::roclet("type"))



}
#' @export
roxy_tag_parse.roxy_tag_type = function(x) {

parts = strsplit(x$raw, ":")[[2]]


if(length(parts)!=2){


roxy_tag_warning("Invalid @type tag, expects <param>: <type> | <type>")

return(NULL)


}


parts=gsub("\\n|\\t", "", parts)
types = strsplit(parts[2], "\\|")[[1]]


x$val=list(list(arg=parts[1]|>trimws(), types=types|>trimws()))



return(x)



}
#' @export
roxy_tag_rd.roxy_tag_type = function(x, base_path,env) {


return(roxygen2::rd_section("type", x$val))



}
#' @export
format.rd_section_type = function(x, ...) {

types = ""

for(val in x$value) {

t = paste0(val$types, collapse=", or ")

t=paste0("  \\item{", val$arg, "}{", t, "}\n")
types=paste0(types, t)
}

return(paste0("\\section{Types}{\n", "\\itemize{\n", types, "}\n", "}\n"))



}



#' @export
roclet_process.roclet_type = function(x, blocks,env,base_path) {

results = 



for(block in blocks) {

tags = block_get_tags(block, "type")

for(tag in tags) {

t = list(value=tag$val, cat="type", file=tag$file)

results=append(results, tag$val)
}
}

return(results)



}
#' @export
roclet_output.roclet_type = function(x, results,base_path,...) {

globals$types=results

return(invisible(NULL))



}
#' Yield
#'
#' Add yield to the roxygen2 documentation.
#'
#' @importFrom roxygen2 roclet roxy_tag_warning block_get_tags roclet_output
#' @importFrom roxygen2 roclet_process roxy_tag_parse rd_section roxy_tag_rd
#'
#' @import roxygen2
#'
#' @export
roclet_yield = function() {


return(roxygen2::roclet("yield"))



}
#' @export
roxy_tag_parse.rody_tag_yield = function(x) {

raw = gsub("\\n|\\t", "", x$raw)

yields = strsplit(raw, "\\|")[[1]]


x$val=roxy(yield=yields|>trimws())



return(x)



}
#' @export
rody_tag_rd.roxy_tag_yield = function(x, base_path,env) {

rd_section("yield", x$val)

}
#' @export
format.rd_section_yield = function(x, ...) {

yield = paste0(x$value$yield, collapse=", or ")


return(paste0("\\yield{", yield, "}\n"))



}
#' @export
roclet_process.roclet_yield = function(x, blocks,env,base_path) {

results = list()



for(block in blocks) {

tags = block_get_tags(block, "yield")

class(tags)="list"
results=append(results, list(x))
}

return(results)



}
#' @export
roclet_output.roclet_yield = function(x, results,base_path,...) {

globals$yields=results

return(invisible(NULL))



}
