# GENERATED BY VAPOUR
# DO NOT EDIT


write_config = function() {

config = list(types=globals$types, yields=globals$yields)


config)

}
#' Type
#'
#' Add type to the roxygen2 documentation.
#'
#' @importFrom roxygen2 roclet roxy_tag_warning block_get_tags roclet_output
#' @importFrom roxygen2 roclet_process roxy_tag_parse rd_section roxy_tag_rd
#'
#' @import roxygen2
#'
#' @export
roclet_type = function() {


return("type"))



}
#' @export
roxy_tag_parse.roxy_tag_type = function(x) {

parts = x$raw, ":")
parts=parts[[2]]


if(parts)!=2){


"Invalid @type tag, expects <param>: <type> | <type>")

return(NULL)


}


parts="\\n|\\t", "", parts)
types = parts[2], "\\|")[[1]]


x$val=list(list(arg=), types=)))



return(x)



}
#' @export
roxy_tag_rd.roxy_tag_type = function(x,base_path,env) {


return("type", x$val))



}
#' @export
format.rd_section_type = function(x,...) {

types = ""
for(val in x$value) {

t = val$types, collapse=", or ")
t="  \\item{", val$arg, "}{", t, "}\n")
types=types, t)
}



return("\\section{Types}{\n", "\\itemize{\n", types, "}\n", "}\n"))



}
#' @export
roclet_process.roclet_type = function(x,blocks,env,base_path) {

results = list()


for(block in blocks) {

tags = block, "type")
for(tag in tags) {

t = list(value=tag$val, cat="type", file=tag$file)
results=results, tag$val)
}
}



return(results)



}
#' @export
roclet_output.roclet_type = function(x,results,base_path,...) {

globals$types=results

return(NULL))



}


#' Yield
#'
#' Add yield to the roxygen2 documentation.
#'
#' @importFrom roxygen2 roclet roxy_tag_warning block_get_tags roclet_output
#' @importFrom roxygen2 roclet_process roxy_tag_parse rd_section roxy_tag_rd
#'
#' @import roxygen2
#'
#' @export
roclet_yield = function() {


return("yield"))



}
#' @export
roxy_tag_parse.rody_tag_yield = function(x) {

raw = "\\n|\\t", "", x$raw)
yields = raw, "\\|")[[1]]


x$val=list(yield=))



return(x)



}
#' @export
rody_tag_rd.roxy_tag_yield = function(x,base_path,env) {

"yield", x$val)

}
#' @export
format.rd_section_yield = function(x,...) {

yield = x$value$yield, collapse=", or ")

return("\\yield{", yield, "}\n"))



}
#' @export
roclet_process.roclet_yield = function(x,blocks,env,base_path) {

results = list()


for(block in blocks) {

tags = block, "yield")
tags)="list"
results=results, list(x))
}



return(results)



}
#' @export
roclet_output.roclet_yield = function(x,results,base_path,...) {

globals$yields=results

return(NULL))



}
globals = parent=), hash=TRUE)
